[nltk_data] Downloading package punkt to /home/pi/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
----Bot started.----
"For the likes of Phantom or Hamilton, this is a departure to pre-Covid schedules." https://www.whatsonstage.com/london-theatre/news/west-end-shows-schedule-sunday-performances_53496.html
Traceback (most recent call last):
  File "link_wos.py", line 92, in <module>
    main()
  File "link_wos.py", line 84, in main
    api.update_status(status=tweet)
  File "/usr/lib/python2.7/dist-packages/twython/endpoints.py", line 123, in update_status
    return self.post('statuses/update', params=params)
  File "/usr/lib/python2.7/dist-packages/twython/api.py", line 274, in post
    return self.request(endpoint, 'POST', params=params, version=version)
  File "/usr/lib/python2.7/dist-packages/twython/api.py", line 264, in request
    api_call=url)
  File "/usr/lib/python2.7/dist-packages/twython/api.py", line 166, in _request
    raise TwythonError(str(e))
twython.exceptions.TwythonError: ('Connection aborted.', error("(104, 'ECONNRESET')",))
